In [1]:
import pandas as pd
pd.set_option('display.max_columns', 100)
import numpy as np

## GOOGLE APPS

In [8]:
google_play = pd.read_csv('google-play-store-apps/googleplaystore.csv')
print("['Countries dropped', 'Android Ver', 'Current Ver', 'Genres', 'Price']")
google_play.drop(['Android Ver', 'Current Ver', 'Genres', 'Price'], axis=1, inplace=True)
print("Google Play dataset: ", google_play.shape)
google_play.sample(3)

['Countries dropped', 'Android Ver', 'Current Ver', 'Genres', 'Price']
Google Play dataset:  (10841, 9)

,App,Category,Rating,Reviews,Size,Installs,Type,Content Rating,Last Updated
3684,YouTube Studio,VIDEO_PLAYERS,4.3,436921,Varies with device,"10,000,000+",Free,Teen,"June 28, 2018"
5327,Al Jazeera English,NEWS_AND_MAGAZINES,4.1,24456,Varies with device,"1,000,000+",Free,Everyone,"July 24, 2018"
8286,DC Metro Transit,TRAVEL_AND_LOCAL,4.5,339,10M,"5,000+",Paid,Everyone,"May 13, 2018"

## APP STORE

In [9]:
app_store = pd.read_csv('appstore_games.csv')
print("Columns dropped: ['Subtitle' ,'ID', 'URL', 'Icon URL', 'Description', 'Developer', 'Languages', 'Genres']")
app_store.drop(['Subtitle' ,'ID', 'URL', 'Icon URL', 'Description', 'Developer', 'Languages', 'Genres'], axis=1, inplace=True)
print("App Store dataset 2016: ", app_store.shape)
app_store.sample(3)

Columns dropped: ['Subtitle' ,'ID', 'URL', 'Icon URL', 'Description', 'Developer', 'Languages', 'Genres']
App Store dataset 2016:  (17007, 10)

,Name,Average User Rating,User Rating Count,Price,In-app Purchases,Age Rating,Size,Primary Genre,Original Release Date,Current Version Release Date
14205,Grim Defender: Castle Defense,5.0,259.0,0.0,"2.99, 4.99, 8.99, 16.99",9+,140123136.0,Games,28/07/2018,23/03/2019
1750,Lynnsee PopBirds,4.0,48.0,0.0,"0.99, 7.99",4+,16009216.0,Games,27/11/2012,21/12/2017
5542,Ball Poppers - Clash of crazy balls to solve p...,NaN,NaN,0.0,"0.99, 1.99, 3.99, 5.99, 0.99, 1.99, 3.99, 5.99",4+,32423936.0,Games,12/03/2015,21/03/2015

## VGSALES

In [10]:
vg_sales = pd.read_csv('vgsales.csv')
print("Columns dropped: ['Publisher', 'Rank']")
vg_sales.drop(['Publisher', 'Rank'], axis=1, inplace=True)
print("Video Game Sales Dataset: ", vg_sales.shape)
vg_sales.sample(3)

Columns dropped: ['Publisher', 'Rank']
Video Game Sales Dataset:  (16598, 9)

,Name,Platform,Year,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
1457,Lost Planet: Extreme Condition,X360,2006.0,Shooter,1.09,0.04,0.10,0.11,1.34
13971,Galaxy Fight,SAT,1994.0,Fighting,0.00,0.00,0.04,0.00,0.04
4284,The Golden Compass,X360,2007.0,Action,0.30,0.12,0.00,0.04,0.46

## PAN EUROPEAN GAME INFO

In [22]:
pegi_rating = pd.read_csv('PEGI_Ratings_20170907.csv')
print("PEGI dataset: ", pegi_rating.shape)
pegi_rating.sample(3)

PEGI dataset:  (27957, 5)

                  game  rating     platform      genre     release
5464   Daedalic Puzzle     3.0           PC     Puzzle  2014-05-06
1592   Archon: Classic    12.0           PC   Strategy  2011-02-17
8666  Finding Nemo NDS     3.0  Nintendo DS  Adventure  2006-03-17

## GAME-SALES

In [40]:
##SALES
vg_sales2016 = pd.read_csv('games-sales/Video_Games_Sales_as_at_22_Dec_2016.csv')
vg_sales2016.drop(['Publisher', 'Developer', 'User_Count', 'Critic_Count'], axis=1, inplace=True)
print('VG Sales 2016 dataset: ', vg_sales2016.shape)
vg_sales2016.head(3)

VG Sales 2016 dataset:  (16719, 12)

,Name,Platform,Year_of_Release,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,User_Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,82.53,76.0,8.0,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,35.52,82.0,8.3,E

In [41]:
##PS4
vg_sales2016_ps4 = pd.read_csv('games-sales/PS4_GamesSales.csv', sep=',', engine='python')
print('VG Sales 2016 PS4 dataset: ', vg_sales2016_ps4.shape)
vg_sales2016_ps4.head(3)

VG Sales 2016 PS4 dataset:  (1034, 9)

,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,Grand Theft Auto V,2014.0,Action,Rockstar Games,6.06,9.71,0.60,3.02,19.39
1,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,6.18,6.05,0.41,2.44,15.09
2,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,5.26,6.21,0.21,2.26,13.94

In [42]:
##XBOX
vg_sales2016_xbox = pd.read_csv('games-sales/XboxOne_GameSales.csv', sep=',', engine='python')
print('VG Sales 2016 XBOX dataset: ', vg_sales2016_xbox.shape)
vg_sales2016_xbox.head(3)

VG Sales 2016 XBOX dataset:  (613, 10)

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
1,2,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,4.63,2.04,0.02,0.68,7.37
2,3,Call of Duty: WWII,2017.0,Shooter,Activision,3.75,1.91,0.00,0.57,6.23

## VIDEO GAMES 2019  VGCHARTZ.COM

In [43]:
vg_sales2019 = pd.read_csv('vgsales-12-4-2019-short.csv')
print("Columns dropped: ['Rank', 'Publisher', 'Developer', 'Global_Sales']")
vg_sales2019.drop(['Rank', 'Publisher', 'Developer', 'Global_Sales'], axis=1, inplace=True)
print("VG Sales dataset: ", vg_sales2019.shape)
vg_sales2019.head(3)

Columns dropped: ['Rank', 'Publisher', 'Developer', 'Global_Sales']
VG Sales dataset:  (55792, 12)

,Name,Genre,ESRB_Rating,Platform,Critic_Score,User_Score,Total_Shipped,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
0,Wii Sports,Sports,E,Wii,7.7,NaN,82.86,NaN,NaN,NaN,NaN,2006.0
1,Super Mario Bros.,Platform,NaN,NES,10.0,NaN,40.24,NaN,NaN,NaN,NaN,1985.0
2,Mario Kart Wii,Racing,E,Wii,8.2,9.1,37.14,NaN,NaN,NaN,NaN,2008.0

## STEAM 200k

In [15]:
steam = pd.read_csv('steam-200k.csv')
print("Steam database: ", steam.shape)
steam.sample(3)l

Steam database:  (199999, 5)

,151603712,The Elder Scrolls V Skyrim,purchase,1.0,0
122943,76892907,Legacy of Kain Defiance,purchase,1.0,0
186645,47457723,Warlock - Master of the Arcane Powerful Lords,purchase,1.0,0
124999,46028967,FINAL FANTASY VIII,purchase,1.0,0

## GAMES JSON-format

In [16]:
games_json = pd.read_json('games.json')
print("columns dropped: ['url', 'oses', 'developer', 'cloud_saves', 'controller_support', 'overlay', 'single_player', 'achievement', 'multi_player', 'coop', 'leaderboard', 'in_development', 'languages', 'achievements', 'reviews']")
games_json.drop(['url', 'oses', 'developer', 'cloud_saves', 'controller_support', 'overlay', 'single_player', 'achievement', 'multi_player', 'coop', 'leaderboard', 'in_development', 'languages', 'achievements', 'reviews'], axis=1, inplace=True)
print("Games Json Dataset: ", games_json.shape)
games_json.sample(3)

columns dropped: ['url', 'oses', 'developer', 'cloud_saves', 'controller_support', 'overlay', 'single_player', 'achievement', 'multi_player', 'coop', 'leaderboard', 'in_development', 'languages', 'achievements', 'reviews']
Games Json Dataset:  (2742, 8)

,name,price,player_rating,genres,size,rating,release_date,publisher
1358,Guacamelee! Gold Edition,14.99,4.2,"[Action, Combat, Platformer]",627 MB,NaN,2013-08-08T00:00:00+03:00,DrinkBox Studios
1204,Pandora: First Contact - Gold Edition,35.19,3.7,"[Strategy, Simulation, Sci-fi]",604 MB,NaN,2013-11-14T00:00:00+02:00,Slitherine Ltd.
764,THE KING OF FIGHTERS 2002 UNLIMITED MATCH,12.99,4.7,"[Action, Arcade, Fighting]",830 MB,NaN,2015-02-27T00:00:00+02:00,SNK CORPORATION

## STEAM STORE

In [49]:
steam_store = pd.read_csv('steam-store-games/steam.csv')
print("Columns dropped: ['english', 'developer', 'publisher', 'categories', 'steamspy_tags', 'achievements']")
steam_store.drop(['english', 'developer', 'publisher', 'categories', 'steamspy_tags', 'achievements'], axis=1, inplace=True)
print("Steam Store Dataset: ", steam_store.shape)
steam_store.head(3)

Columns dropped: ['english', 'developer', 'publisher', 'categories', 'steamspy_tags', 'achievements']
Steam Store Dataset:  (27075, 12)

,appid,name,release_date,platforms,required_age,genres,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price
0,10,Counter-Strike,2000-11-01,windows;mac;linux,0,Action,124534,3339,17612,317,10000000-20000000,7.19
1,20,Team Fortress Classic,1999-04-01,windows;mac;linux,0,Action,3318,633,277,62,5000000-10000000,3.99
2,30,Day of Defeat,2003-05-01,windows;mac;linux,0,Action,3416,398,187,34,5000000-10000000,3.99

In [34]:
steam_store_spy = pd.read_csv('steam-store-games/steamspy_tag_data.csv')
print("Steam Store Spy Dataset: ", steam_store_spy.shape)
steam_store_spy.sample(3)

Steam Store Spy Dataset:  (29022, 372)

,appid,1980s,1990s,2.5d,2d,2d_fighter,360_video,3d,3d_platformer,3d_vision,4_player_local,4x,6dof,atv,abstract,action,action_rpg,action_adventure,addictive,adventure,agriculture,aliens,alternate_history,america,animation_&_modeling,anime,arcade,arena_shooter,artificial_intelligence,assassin,asynchronous_multiplayer,atmospheric,audio_production,bmx,base_building,baseball,based_on_a_novel,basketball,batman,battle_royale,beat_em_up,beautiful,benchmark,bikes,blood,board_game,bowling,building,bullet_hell,bullet_time,...,text_based,third_person,third_person_shooter,thriller,time_attack,time_management,time_manipulation,time_travel,top_down,top_down_shooter,touch_friendly,tower_defense,trackir,trading,trading_card_game,trains,transhumanism,turn_based,turn_based_combat,turn_based_strategy,turn_based_tactics,tutorial,twin_stick_shooter,typing,underground,underwater,unforgiving,utilities,vr,vr_only,vampire,video_production,villain_protagonist,violent,visual_novel,voice_control,voxel,walking_simulator,war,wargame,warhammer_40k,web_publishing,werewolves,western,word_game,world_war_i,world_war_ii,wrestling,zombies,e_sports
3664,304690,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19397,735280,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24335,871230,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [51]:
steam_features = pd.read_csv('games-features.csv')
print(steam_features.shape)
steam_features.head(3)

(13357, 78)

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,MovieCount,PackageCount,RecommendationCount,PublisherCount,ScreenshotCount,SteamSpyOwners,SteamSpyOwnersVariance,SteamSpyPlayersEstimate,SteamSpyPlayersVariance,AchievementCount,AchievementHighlightedCount,ControllerSupport,IsFree,FreeVerAvail,PurchaseAvail,SubscriptionAvail,PlatformWindows,PlatformLinux,PlatformMac,PCReqsHaveMin,PCReqsHaveRec,LinuxReqsHaveMin,LinuxReqsHaveRec,MacReqsHaveMin,MacReqsHaveRec,CategorySinglePlayer,CategoryMultiplayer,CategoryCoop,CategoryMMO,CategoryInAppPurchase,CategoryIncludeSrcSDK,CategoryIncludeLevelEditor,CategoryVRSupport,GenreIsNonGame,GenreIsIndie,GenreIsAction,GenreIsAdventure,GenreIsCasual,GenreIsStrategy,GenreIsRPG,GenreIsSimulation,GenreIsEarlyAccess,GenreIsFreeToPlay,GenreIsSports,GenreIsRacing,GenreIsMassivelyMultiplayer,PriceCurrency,PriceInitial,PriceFinal,SupportEmail,SupportURL,AboutText,Background,ShortDescrip,DetailedDescrip,DRMNotice,ExtUserAcctNotice,HeaderImage,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
0,10,10,Counter-Strike,Counter-Strike,Nov 1 2000,0,0,1,0,88,0,1,68991,1,13,13033334,92789,9140731,78136,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,http://steamcommunity.com/app/10,Play the worlds number 1 online action game. E...,http://cdn.akamai.steamstatic.com/steam/apps/1...,,Play the worlds number 1 online action game. E...,,,http://cdn.akamai.steamstatic.com/steam/apps/1...,,,English French German Italian Spanish Simplifi...,None,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
1,20,20,Team Fortress Classic,Team Fortress Classic,Apr 1 1999,0,0,1,0,0,0,1,2439,1,5,5399140,60368,753627,22699,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,One of the most popular online action games of...,http://cdn.akamai.steamstatic.com/steam/apps/2...,,One of the most popular online action games of...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English French German Italian Spanish,None,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
2,30,30,Day of Defeat,Day of Defeat,May 1 2003,0,0,1,0,79,0,1,2319,1,5,7621102,71499,1709740,34145,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,Enlist in an intense brand of Axis vs. Allied ...,http://cdn.akamai.steamstatic.com/steam/apps/3...,,Enlist in an intense brand of Axis vs. Allied ...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English French German Italian Spanish,http://www.dayofdefeat.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,

## VANDAL Spanish Platform

In [20]:
vandal = pd.read_csv('vandal.csv')
print("columns dropped: ['id', 'developer', 'preview', 'url']")
vandal.drop(['id', 'developer', 'preview', 'url'], axis=1, inplace=True)
print("Vandal Dataset: ", vandal.shape)
vandal.sample(3)

columns dropped: ['id', 'developer', 'preview', 'url']
Vandal Dataset:  (11910, 6)

,game,platform,website_rating,user_rating,release,classification
2958,Extreme Exorcism,Xbox One,7.5,None,23/9/2015,PEGI +7
9600,Super Mario Run,Android,None,6.42,23/3/2017,None
606,Avatar,PS3,8.5,7.8,3/12/2009,PEGI +12